insert into users (name, password, email, homepage, created_at, updated_at) values ('redraiment', '123', 'redraiment@gmail.com', 'http://weibo.com/redraiment', current_timestamp, current_timestamp);

insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 0, '数据结构', '数据结构', 1, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 0, '设计模式', '设计模式', 2, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 1, '线性表', '线性表', 1, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 1, '树', '树', 2, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 1, '图', '图', 3, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 2, '工厂模式', '工厂模式', 1, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 2, '适配器模式', '适配器模式', 2, current_timestamp, current_timestamp);
insert into issues (user_id, parent_id, name, description, sort, created_at, updated_at) values (1, 2, '模板模式', '模板模式', 3, current_timestamp, current_timestamp);

insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 0, 'Java', 1, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 0, 'Ruby', 2, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 0, 'Python', 3, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 1, 'Seam', 1, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 1, 'Spring', 2, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 1, 'Hibernate', 3, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 2, 'Rails', 1, current_timestamp, current_timestamp);
insert into tools (user_id, parent_id, name, sort, created_at, updated_at) values (1, 2, 'Sinatra', 2, current_timestamp, current_timestamp);

insert into solutions (issue_id, created_at, updated_at) values (1, current_timestamp, current_timestamp);
insert into solutions (issue_id, created_at, updated_at) values (1, current_timestamp, current_timestamp);

insert into tags (solution_id, tool_id, created_at, updated_at) values (1, 1, current_timestamp, current_timestamp);
insert into tags (solution_id, tool_id, created_at, updated_at) values (2, 1, current_timestamp, current_timestamp);
insert into tags (solution_id, tool_id, created_at, updated_at) values (2, 4, current_timestamp, current_timestamp);

insert into snippets (user_id, solution_id, lexer_id, code, comment, created_at, updated_at) values (1, 1, 124, 'Java version 1', 'java v1', current_timestamp, current_timestamp);
insert into snippets (user_id, solution_id, lexer_id, code, comment, created_at, updated_at) values (1, 1, 124, 'Java version 2', 'java v2', current_timestamp, current_timestamp);
insert into snippets (user_id, solution_id, lexer_id, code, comment, created_at, updated_at) values (1, 2, 124, 'Java+Hibernate version 1', 'java+orm v1', current_timestamp, current_timestamp);

insert into lexers (name, module, class, created_at, updated_at) values ('ABAP', 'pygments.lexers.other', 'ABAPLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With ActionScript Target', 'pygments.lexers.parsers', 'AntlrActionScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With C# Target', 'pygments.lexers.parsers', 'AntlrCSharpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With CPP Target', 'pygments.lexers.parsers', 'AntlrCppLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With Java Target', 'pygments.lexers.parsers', 'AntlrJavaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With ObjectiveC Target', 'pygments.lexers.parsers', 'AntlrObjectiveCLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With Perl Target', 'pygments.lexers.parsers', 'AntlrPerlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With Python Target', 'pygments.lexers.parsers', 'AntlrPythonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR With Ruby Target', 'pygments.lexers.parsers', 'AntlrRubyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ANTLR', 'pygments.lexers.parsers', 'AntlrLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ActionScript 3', 'pygments.lexers.web', 'ActionScript3Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ActionScript', 'pygments.lexers.web', 'ActionScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ada', 'pygments.lexers.compiled', 'AdaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ApacheConf', 'pygments.lexers.text', 'ApacheConfLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('AppleScript', 'pygments.lexers.other', 'AppleScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('AspectJ', 'pygments.lexers.jvm', 'AspectJLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Asymptote', 'pygments.lexers.other', 'AsymptoteLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('AutoIt', 'pygments.lexers.other', 'AutoItLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Awk', 'pygments.lexers.other', 'AwkLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('BBCode', 'pygments.lexers.text', 'BBCodeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('BUGS', 'pygments.lexers.math', 'BugsLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Base Makefile', 'pygments.lexers.text', 'BaseMakefileLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Bash Session', 'pygments.lexers.shell', 'BashSessionLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Bash', 'pygments.lexers.shell', 'BashLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Batchfile', 'pygments.lexers.shell', 'BatchLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Befunge', 'pygments.lexers.other', 'BefungeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('BlitzMax', 'pygments.lexers.compiled', 'BlitzMaxLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Boo', 'pygments.lexers.dotnet', 'BooLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Brainfuck', 'pygments.lexers.other', 'BrainfuckLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Bro', 'pygments.lexers.other', 'BroLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('C#', 'pygments.lexers.dotnet', 'CSharpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('C', 'pygments.lexers.compiled', 'CLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('C++', 'pygments.lexers.compiled', 'CppLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CBM BASIC V2', 'pygments.lexers.other', 'CbmBasicV2Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CFEngine3', 'pygments.lexers.other', 'Cfengine3Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CMake', 'pygments.lexers.text', 'CMakeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('COBOL', 'pygments.lexers.compiled', 'CobolLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('COBOLFree', 'pygments.lexers.compiled', 'CobolFreeformatLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS', 'pygments.lexers.web', 'CssLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Django/Jinja', 'pygments.lexers.templates', 'CssDjangoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Genshi Text', 'pygments.lexers.templates', 'CssGenshiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Lasso', 'pygments.lexers.templates', 'LassoCssLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Mako', 'pygments.lexers.templates', 'MakoCssLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Myghty', 'pygments.lexers.templates', 'MyghtyCssLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+PHP', 'pygments.lexers.templates', 'CssPhpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Ruby', 'pygments.lexers.templates', 'CssErbLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CSS+Smarty', 'pygments.lexers.templates', 'CssSmartyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CUDA', 'pygments.lexers.compiled', 'CudaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ceylon', 'pygments.lexers.jvm', 'CeylonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Cheetah', 'pygments.lexers.templates', 'CheetahLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Clojure', 'pygments.lexers.jvm', 'ClojureLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('CoffeeScript', 'pygments.lexers.web', 'CoffeeScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Coldfusion HTML', 'pygments.lexers.templates', 'ColdfusionHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Common Lisp', 'pygments.lexers.functional', 'CommonLispLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Coq', 'pygments.lexers.functional', 'CoqLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Croc', 'pygments.lexers.agile', 'CrocLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Cython', 'pygments.lexers.compiled', 'CythonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('D', 'pygments.lexers.compiled', 'DLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('DTD', 'pygments.lexers.web', 'DtdLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Darcs Patch', 'pygments.lexers.text', 'DarcsPatchLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Dart', 'pygments.lexers.web', 'DartLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Debian Control file', 'pygments.lexers.text', 'DebianControlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Debian Sourcelist', 'pygments.lexers.text', 'SourcesListLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Delphi', 'pygments.lexers.compiled', 'DelphiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Diff', 'pygments.lexers.text', 'DiffLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Django/Jinja', 'pygments.lexers.templates', 'DjangoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Duel', 'pygments.lexers.web', 'DuelLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Dylan session', 'pygments.lexers.compiled', 'DylanConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Dylan', 'pygments.lexers.compiled', 'DylanLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('DylanLID', 'pygments.lexers.compiled', 'DylanLidLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ECL', 'pygments.lexers.other', 'ECLLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ERB', 'pygments.lexers.templates', 'ErbLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Elixir iex session', 'pygments.lexers.functional', 'ElixirConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Elixir', 'pygments.lexers.functional', 'ElixirLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Embedded Ragel', 'pygments.lexers.parsers', 'RagelEmbeddedLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Erlang erl session', 'pygments.lexers.functional', 'ErlangShellLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Erlang', 'pygments.lexers.functional', 'ErlangLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Evoque', 'pygments.lexers.templates', 'EvoqueLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('FSharp', 'pygments.lexers.dotnet', 'FSharpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Factor', 'pygments.lexers.agile', 'FactorLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Fancy', 'pygments.lexers.agile', 'FancyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Fantom', 'pygments.lexers.compiled', 'FantomLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Felix', 'pygments.lexers.compiled', 'FelixLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Fortran', 'pygments.lexers.compiled', 'FortranLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('FoxPro', 'pygments.lexers.foxpro', 'FoxProLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('GAS', 'pygments.lexers.asm', 'GasLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('GLSL', 'pygments.lexers.compiled', 'GLShaderLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Genshi Text', 'pygments.lexers.templates', 'GenshiTextLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Genshi', 'pygments.lexers.templates', 'GenshiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Gettext Catalog', 'pygments.lexers.text', 'GettextLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Gherkin', 'pygments.lexers.other', 'GherkinLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Gnuplot', 'pygments.lexers.other', 'GnuplotLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Go', 'pygments.lexers.compiled', 'GoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('GoodData-CL', 'pygments.lexers.other', 'GoodDataCLLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Gosu Template', 'pygments.lexers.jvm', 'GosuTemplateLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Gosu', 'pygments.lexers.jvm', 'GosuLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Groff', 'pygments.lexers.text', 'GroffLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Groovy', 'pygments.lexers.jvm', 'GroovyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML', 'pygments.lexers.web', 'HtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Cheetah', 'pygments.lexers.templates', 'CheetahHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Django/Jinja', 'pygments.lexers.templates', 'HtmlDjangoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Evoque', 'pygments.lexers.templates', 'EvoqueHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Genshi', 'pygments.lexers.templates', 'HtmlGenshiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Lasso', 'pygments.lexers.templates', 'LassoHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Mako', 'pygments.lexers.templates', 'MakoHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Myghty', 'pygments.lexers.templates', 'MyghtyHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+PHP', 'pygments.lexers.templates', 'HtmlPhpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Smarty', 'pygments.lexers.templates', 'HtmlSmartyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTML+Velocity', 'pygments.lexers.templates', 'VelocityHtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('HTTP', 'pygments.lexers.text', 'HttpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Haml', 'pygments.lexers.web', 'HamlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Haskell', 'pygments.lexers.functional', 'HaskellLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Hxml', 'pygments.lexers.text', 'HxmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Hybris', 'pygments.lexers.other', 'HybrisLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('IDL', 'pygments.lexers.math', 'IDLLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('INI', 'pygments.lexers.text', 'IniLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('IRC logs', 'pygments.lexers.text', 'IrcLogsLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Io', 'pygments.lexers.agile', 'IoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ioke', 'pygments.lexers.jvm', 'IokeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JAGS', 'pygments.lexers.math', 'JagsLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JSON', 'pygments.lexers.web', 'JsonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Jade', 'pygments.lexers.web', 'JadeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Java Server Page', 'pygments.lexers.templates', 'JspLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Java', 'pygments.lexers.jvm', 'JavaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript', 'pygments.lexers.web', 'JavascriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Cheetah', 'pygments.lexers.templates', 'CheetahJavascriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Django/Jinja', 'pygments.lexers.templates', 'JavascriptDjangoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Genshi Text', 'pygments.lexers.templates', 'JavascriptGenshiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Lasso', 'pygments.lexers.templates', 'LassoJavascriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Mako', 'pygments.lexers.templates', 'MakoJavascriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Myghty', 'pygments.lexers.templates', 'MyghtyJavascriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+PHP', 'pygments.lexers.templates', 'JavascriptPhpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Ruby', 'pygments.lexers.templates', 'JavascriptErbLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('JavaScript+Smarty', 'pygments.lexers.templates', 'JavascriptSmartyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Julia console', 'pygments.lexers.math', 'JuliaConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Julia', 'pygments.lexers.math', 'JuliaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Kconfig', 'pygments.lexers.other', 'KconfigLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Koka', 'pygments.lexers.functional', 'KokaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Kotlin', 'pygments.lexers.jvm', 'KotlinLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('LLVM', 'pygments.lexers.asm', 'LlvmLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Lasso', 'pygments.lexers.web', 'LassoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Lighttpd configuration file', 'pygments.lexers.text', 'LighttpdConfLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Literate Haskell', 'pygments.lexers.functional', 'LiterateHaskellLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('LiveScript', 'pygments.lexers.web', 'LiveScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Logos', 'pygments.lexers.compiled', 'LogosLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Logtalk', 'pygments.lexers.other', 'LogtalkLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Lua', 'pygments.lexers.agile', 'LuaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MAQL', 'pygments.lexers.other', 'MaqlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MOOCode', 'pygments.lexers.other', 'MOOCodeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MXML', 'pygments.lexers.web', 'MxmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Makefile', 'pygments.lexers.text', 'MakefileLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Mako', 'pygments.lexers.templates', 'MakoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Mason', 'pygments.lexers.templates', 'MasonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Matlab session', 'pygments.lexers.math', 'MatlabSessionLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Matlab', 'pygments.lexers.math', 'MatlabLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MiniD', 'pygments.lexers.agile', 'MiniDLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Modelica', 'pygments.lexers.other', 'ModelicaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Modula-2', 'pygments.lexers.compiled', 'Modula2Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MoinMoin/Trac Wiki markup', 'pygments.lexers.text', 'MoinWikiLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Monkey', 'pygments.lexers.compiled', 'MonkeyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MoonScript', 'pygments.lexers.agile', 'MoonScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Mscgen', 'pygments.lexers.other', 'MscgenLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MuPAD', 'pygments.lexers.math', 'MuPADLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('MySQL', 'pygments.lexers.sql', 'MySqlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Myghty', 'pygments.lexers.templates', 'MyghtyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('NASM', 'pygments.lexers.asm', 'NasmLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('NSIS', 'pygments.lexers.other', 'NSISLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Nemerle', 'pygments.lexers.dotnet', 'NemerleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('NewLisp', 'pygments.lexers.functional', 'NewLispLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Newspeak', 'pygments.lexers.other', 'NewspeakLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Nginx configuration file', 'pygments.lexers.text', 'NginxConfLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Nimrod', 'pygments.lexers.compiled', 'NimrodLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('NumPy', 'pygments.lexers.math', 'NumPyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('OCaml', 'pygments.lexers.functional', 'OcamlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Objective-C', 'pygments.lexers.compiled', 'ObjectiveCLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Objective-C++', 'pygments.lexers.compiled', 'ObjectiveCppLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Objective-J', 'pygments.lexers.web', 'ObjectiveJLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Octave', 'pygments.lexers.math', 'OctaveLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ooc', 'pygments.lexers.compiled', 'OocLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Opa', 'pygments.lexers.functional', 'OpaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('OpenEdge ABL', 'pygments.lexers.other', 'OpenEdgeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PHP', 'pygments.lexers.web', 'PhpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PL/pgSQL', 'pygments.lexers.sql', 'PlPgsqlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('POVRay', 'pygments.lexers.other', 'PovrayLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Perl', 'pygments.lexers.agile', 'PerlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PostScript', 'pygments.lexers.other', 'PostScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PostgreSQL SQL dialect', 'pygments.lexers.sql', 'PostgresLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PostgreSQL console (psql)', 'pygments.lexers.sql', 'PostgresConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PowerShell', 'pygments.lexers.shell', 'PowerShellLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Prolog', 'pygments.lexers.compiled', 'PrologLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Properties', 'pygments.lexers.text', 'PropertiesLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Protocol Buffer', 'pygments.lexers.other', 'ProtoBufLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Puppet', 'pygments.lexers.other', 'PuppetLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('PyPy Log', 'pygments.lexers.text', 'PyPyLogLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Python 3', 'pygments.lexers.agile', 'Python3Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Python 3.0 Traceback', 'pygments.lexers.agile', 'Python3TracebackLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Python Traceback', 'pygments.lexers.agile', 'PythonTracebackLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Python console session', 'pygments.lexers.agile', 'PythonConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Python', 'pygments.lexers.agile', 'PythonLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('QML', 'pygments.lexers.web', 'QmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('RConsole', 'pygments.lexers.math', 'RConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('REBOL', 'pygments.lexers.other', 'RebolLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('RHTML', 'pygments.lexers.templates', 'RhtmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('RPMSpec', 'pygments.lexers.other', 'RPMSpecLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Racket', 'pygments.lexers.functional', 'RacketLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in C Host', 'pygments.lexers.parsers', 'RagelCLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in CPP Host', 'pygments.lexers.parsers', 'RagelCppLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in D Host', 'pygments.lexers.parsers', 'RagelDLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in Java Host', 'pygments.lexers.parsers', 'RagelJavaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in Objective C Host', 'pygments.lexers.parsers', 'RagelObjectiveCLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel in Ruby Host', 'pygments.lexers.parsers', 'RagelRubyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ragel', 'pygments.lexers.parsers', 'RagelLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Raw token data', 'pygments.lexers.special', 'RawTokenLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Rd', 'pygments.lexers.math', 'RdLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Redcode', 'pygments.lexers.other', 'RedcodeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('RobotFramework', 'pygments.lexers._robotframeworklexer', 'RobotFrameworkLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ruby irb session', 'pygments.lexers.agile', 'RubyConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Ruby', 'pygments.lexers.agile', 'RubyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Rust', 'pygments.lexers.compiled', 'RustLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('S', 'pygments.lexers.math', 'SLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('SCSS', 'pygments.lexers.web', 'ScssLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('SQL', 'pygments.lexers.sql', 'SqlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Sass', 'pygments.lexers.web', 'SassLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Scala', 'pygments.lexers.jvm', 'ScalaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Scalate Server Page', 'pygments.lexers.templates', 'SspLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Scaml', 'pygments.lexers.web', 'ScamlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Scheme', 'pygments.lexers.functional', 'SchemeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Scilab', 'pygments.lexers.math', 'ScilabLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Shell Session', 'pygments.lexers.shell', 'ShellSessionLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Smali', 'pygments.lexers.dalvik', 'SmaliLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Smalltalk', 'pygments.lexers.other', 'SmalltalkLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Smarty', 'pygments.lexers.templates', 'SmartyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Snobol', 'pygments.lexers.other', 'SnobolLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('SourcePawn', 'pygments.lexers.other', 'SourcePawnLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('SquidConf', 'pygments.lexers.text', 'SquidConfLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Stan', 'pygments.lexers.math', 'StanLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Standard ML', 'pygments.lexers.functional', 'SMLLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Tcl', 'pygments.lexers.agile', 'TclLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Tcsh', 'pygments.lexers.shell', 'TcshLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('TeX', 'pygments.lexers.text', 'TexLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Tea', 'pygments.lexers.templates', 'TeaTemplateLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Text only', 'pygments.lexers.special', 'TextLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Treetop', 'pygments.lexers.parsers', 'TreetopLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('TypeScript', 'pygments.lexers.web', 'TypeScriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('UrbiScript', 'pygments.lexers.other', 'UrbiscriptLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('VB.net', 'pygments.lexers.dotnet', 'VbNetLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('VGL', 'pygments.lexers.other', 'VGLLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Vala', 'pygments.lexers.compiled', 'ValaLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Velocity', 'pygments.lexers.templates', 'VelocityLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('VimL', 'pygments.lexers.text', 'VimLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML', 'pygments.lexers.web', 'XmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Cheetah', 'pygments.lexers.templates', 'CheetahXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Django/Jinja', 'pygments.lexers.templates', 'XmlDjangoLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Evoque', 'pygments.lexers.templates', 'EvoqueXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Lasso', 'pygments.lexers.templates', 'LassoXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Mako', 'pygments.lexers.templates', 'MakoXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Myghty', 'pygments.lexers.templates', 'MyghtyXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+PHP', 'pygments.lexers.templates', 'XmlPhpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Ruby', 'pygments.lexers.templates', 'XmlErbLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Smarty', 'pygments.lexers.templates', 'XmlSmartyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XML+Velocity', 'pygments.lexers.templates', 'VelocityXmlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XQuery', 'pygments.lexers.web', 'XQueryLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('XSLT', 'pygments.lexers.web', 'XsltLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('Xtend', 'pygments.lexers.jvm', 'XtendLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('YAML', 'pygments.lexers.text', 'YamlLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('aspx-cs', 'pygments.lexers.dotnet', 'CSharpAspxLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('aspx-vb', 'pygments.lexers.dotnet', 'VbNetAspxLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('autohotkey', 'pygments.lexers.other', 'AutohotkeyLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('c-objdump', 'pygments.lexers.asm', 'CObjdumpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('ca65', 'pygments.lexers.asm', 'Ca65Lexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('cfstatement', 'pygments.lexers.templates', 'ColdfusionLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('cpp-objdump', 'pygments.lexers.asm', 'CppObjdumpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('d-objdump', 'pygments.lexers.asm', 'DObjdumpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('dg', 'pygments.lexers.agile', 'DgLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('eC', 'pygments.lexers.compiled', 'ECLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('haXe', 'pygments.lexers.web', 'HaxeLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('objdump', 'pygments.lexers.asm', 'ObjdumpLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('reStructuredText', 'pygments.lexers.text', 'RstLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('reg', 'pygments.lexers.text', 'RegeditLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('sqlite3con', 'pygments.lexers.sql', 'SqliteConsoleLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('systemverilog', 'pygments.lexers.hdl', 'SystemVerilogLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('verilog', 'pygments.lexers.hdl', 'VerilogLexer', current_timestamp, current_timestamp);
insert into lexers (name, module, class, created_at, updated_at) values ('vhdl', 'pygments.lexers.hdl', 'VhdlLexer', current_timestamp, current_timestamp);
